on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev libxext-dev libxxf86vm-dev libxrandr-dev libxinerama-dev libxcursor-dev libxcomposite-dev \
          libvulkan-dev libgl-dev libsdl2-dev \
          libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev \
          libpulse-dev libfreetype-dev libfontconfig-dev \
          libgnutls28-dev libdbus-1-dev gettext
    - name: Download llvm-mingw toolchain
      run: |
        set -xe
        wget https://github.com/mstorsjo/llvm-mingw/releases/download/20260602/llvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64.tar.xz
        echo -e "e71b61c968f65f94ed3878ca22ab663d7854d91c053c1b8a824ac2f1c9a18503\tllvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64.tar.xz" | sha256sum --check
        tar xvf llvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64.tar.xz
        mkdir /opt/llvm-mingw
        mv llvm-mingw-20260602-ucrt-ubuntu-22.04-aarch64/* /opt/llvm-mingw/
        ls /opt/llvm-mingw/bin
        echo "/opt/llvm-mingw/bin" >> $GITHUB_PATH
    - name: Download Wine Code
      uses: actions/checkout@v6
      with:
        repository: wine-mirror/wine
        ref: 2cac6ccf33c0807f374dc96f5a20e35a2da86157 # https://gitlab.winehq.org/wine/wine/-/tags/wine-11.10
        path: wine
    - name: Download FEX-emu Code
      uses: actions/checkout@v6
      with:
        repository: FEX-emu/FEX
        ref: a04b0241c2fe3911729842205cd8643981108aad # https://github.com/FEX-Emu/FEX/releases/tag/FEX-2605
        path: fex-emu
    - name: Configure Wine
      run: |
        cd wine
        ./configure --enable-archs=arm64ec,aarch64,i386 --prefix=/opt/wine-arm64ec --with-mingw=clang --disable-tests
    - name: Build Wine
      run: cd wine && make -j$(nproc)
    - name: Install Wine
      run: cd wine && sudo --preserve-env=PATH make install -j$(nproc)
    - name: Build FEX-emu (Arm64EC)
      run: |
        cd fex-emu
        mkdir build-arm64ec
        cd build-arm64ec
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../Data/CMake/toolchain_mingw.cmake -DCMAKE_INSTALL_LIBDIR=/opt/wine-arm64ec/lib/wine/aarch64-windows -DENABLE_LTO=False -DMINGW_TRIPLE=arm64ec-w64-mingw32 -DBUILD_TESTING=False -DENABLE_JEMALLOC_GLIBC_ALLOC=False -DCMAKE_INSTALL_PREFIX=/opt/wine-arm64ec ..
        ninja
        sudo ninja install
    - name: Build FEX-emu (WoW64 x86)
      run: |
        cd fex-emu
        mkdir build-wow64
        cd build-wow64
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../Data/CMake/toolchain_mingw.cmake -DCMAKE_INSTALL_LIBDIR=/opt/wine-arm64ec/lib/wine/aarch64-windows -DENABLE_LTO=False -DMINGW_TRIPLE=aarch64-w64-mingw32 -DBUILD_TESTING=False -DENABLE_JEMALLOC_GLIBC_ALLOC=False -DCMAKE_INSTALL_PREFIX=/opt/wine-arm64ec ..
        ninja
        sudo ninja install
    - name: Archive everything
      run: |
        cd /opt/wine-arm64ec
        tar czf $GITHUB_WORKSPACE/wine-arm64ec.tar.gz .
    - uses: actions/upload-artifact@v7
      with:
        path: wine-arm64ec.tar.gz
        archive: false
        compression-level: 0